export const END_MESSAGES = [
  "This recipe brought to you by: just the recipe. That's it. That's the sponsor. 🎯",
  "Fun fact: You just saved 12 minutes not reading about why this blogger's spouse 'absolutely adores' this dish. 💑",
  "We removed 17 paragraphs about a life-changing trip to Italy. You're welcome. 🍝",
  "Recipe websites 🤝 Novels about someone's journey to discovering paprika",
  "Plot twist: We don't care that it was 'a crisp autumn morning' when this recipe was discovered. 🍂",
  "Tastly: Because 'Jump to Recipe' buttons shouldn't need to exist. ⏩",
  "Dear Food Bloggers: We're not saying your stories aren't interesting, but... well, actually, that's exactly what we're saying. 📝",
  "Just like grandma used to make, minus grandma's 45-minute backstory. 👵",
  "We'll never tell you how this recipe changed our marriage. (It didn't.) 💍",
  "Tastly: For people who search 'chicken recipe' and actually want a chicken recipe. 🍗",
  "We cut the fluff so you can get to the stuff. ✂️",
  "We just saved you approximately 7 minutes of scrolling. You're welcome! 😉",
  "No life stories were read in the making of this recipe. 🙌",
  "We cut through 12 paragraphs about someone's trip to Italy so you didn't have to. 🍝",
  "Zero stories, 100% recipe. That's how we roll. 🍪",
  "Recipe extracted, life story deleted. Enjoy! 🥂",
  "Tastly: Because nobody has time to read about your dog's reaction to banana bread. 🐕🍌",
  "We removed approximately 1,500 unnecessary words to bring you this recipe. 📝✂️",
  "Life is too short to scroll through food blogs. You're welcome. ⏱️"
];

export const TAGLINES = [
  { text: "No ads ever.", icon: "ban" },
  { text: "No scrolling required.", icon: "mouse" },
  { text: "No ads, no life stories — just recipes.", icon: "book-open" },
  { text: "Ad-free forever.", icon: "shield-check" },
  { text: "Recipes without the family history lesson.", icon: "academic-cap" },
  { text: "Because recipes shouldn't come with a memoir.", icon: "book" },
  { text: "Absolutely zero childhood anecdotes.", icon: "x-circle" },
  { text: "Zero stories about how this casserole saved a marriage.", icon: "heart" },
  { text: "No ads or life stories. Ever.", icon: "ban" },
  { text: "Skip the novel, get the recipe.", icon: "fast-forward" },
  { text: "We won't tell you about our grandmother's trip to Italy.", icon: "globe" },
  { text: "No pop-ups asking about your newsletter preferences.", icon: "mail" },
  { text: "No 'Jump to Recipe' button needed.", icon: "arrow-down" },
  { text: "No paragraphs before the ingredients.", icon: "document-text" },
  { text: "Recipes without the family history lesson.", icon: "academic-cap" },
  { text: "No scrolling marathon required.", icon: "mouse" },
  { text: "We don't care what your kids think about this recipe.", icon: "user-group" },
  { text: "No 'Pin this!' buttons every 3 paragraphs.", icon: "photograph" },
  { text: "Recipes that get to the point.", icon: "lightning-bolt" }
]; 